# Docker and Docker Compose based environment for phpMyAdmin.
# See https://github.com/docksal/docksal for more information and documentation.

version: "2"

services:
  # Web node
  web:
    extends:
      file: .docksal/docksal-services.yml
      service: web
    environment:
      - VIRTUAL_HOST=phpmyadmin.docksal

  # CLI node
  cli:
    extends:
      file: .docksal/docksal-services.yml
      service: cli
